name: Test Deploy

on:
  push:
    branches: [ "test_deploy" ]
  pull_request:
    branches: [ "test_deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -r linux-x64 --self-contained -o ~/app 
    - name: Compress the app folder (using tar)
      run: |
        zip -r ~/app.zip ~/app  
        sshpass ${{ secrets.PASSWORD }} scp ~/app.zip ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/ 
    # - name: Copy build files to server
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: 22
    #     source: "~/app.zip" 
    #     target: "~/"
    # -name: Move build files to output
    #   run: | 
    #     sudo systemctl stop kestrel_app.service 
    #     sudo rsync -av --delete /home/ci_user/app/ /var/www/app 
    #     sudo systemctl start kestrel_app.service 
    #     sudo systemctl reload nginx
