name: Test Deploy

on:
  push:
    branches: [ "test_deploy" ]
  pull_request:
    branches: [ "test_deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore
    
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -r linux-x64 --self-contained -o shop_dotnet_linux_x64 
    
    - name: Compress the app folder (using tar)
      run: |
        pwd
        ls 
        tar -czvf shop_dotnet_linux_x64.tar.gz shop_dotnet_linux_x64 
        sshpass -p '${{ secrets.PASSWORD }}' scp -o StrictHostKeyChecking=no shop_dotnet_linux_x64.tar.gz '${{ secrets.USERNAME }}'@'${{ secrets.HOST }}':~/ 
    
    # -name: Move build files to output
    #   run: | 
    #     sshpass -p '${{ secrets.PASSWORD }}' ssh -o StrictHostKeyChecking=no '${{ secrets.USERNAME }}'@'${{ secrets.HOST }}' 'sudo systemctl stop kestrel_app.service; sudo rsync -av --delete /home/ci_user/app/ /var/www/app; sudo systemctl start kestrel_app.service; sudo systemctl reload nginx'
